name: "Cypress report action"
description: "Basic report added to the pull request as a comment with summary and detailed failures table using github actions."
icon: alert-triangle
color: green
inputs:
  token:
    description: "Github token"
    required: true
  pathname:
    description: "Full pathname to the mochawesome report JSON file"
    required: true
    default: "test/"
  title:
    description: "Title in the comment"
    default: "## :evergreen_tree: Cypress report"
    required: false
  always:
    description: "Should it be shown always or it should be deleted when there are no failures"
    required: false
    default: true
runs:
  using: "composite"
  steps:
    - name: install dependencies
      run: npm install @actions/core@1.10 @actions/github@6.0 @aki77/actions-replace-comment@0.6 markdown-table@3.0
      shell: bash

    - name: run
      run: node $GITHUB_ACTION_PATH/index.js  ${{ inputs.pathname }} ${{ inputs.token }} ${{ inputs.title }} ${{ inputs.always }}
      shell: bash
